<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Seat Allocation - {{ $run->exam->title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10pt;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .hall-section {
            page-break-after: always;
            margin-bottom: 40px;
        }
        .hall-name {
            font-size: 14pt;
            font-weight: bold;
            margin-bottom: 10px;
            border-bottom: 2px solid #333;
            padding-bottom: 5px;
        }
        .grid-container {
            width: 100%;
            margin-top: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid #333;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f0f0f0;
            font-weight: bold;
        }
        .seat-grid {
            display: table;
            width: 100%;
            margin-top: 20px;
        }
        .seat-row {
            display: table-row;
        }
        .seat-cell {
            display: table-cell;
            border: 1px solid #ccc;
            padding: 5px;
            text-align: center;
            min-width: 60px;
            min-height: 40px;
            font-size: 8pt;
        }
        .seat-cell.occupied {
            background-color: #e8f4f8;
        }
        .seat-number {
            font-weight: bold;
            font-size: 9pt;
        }
        .footer {
            margin-top: 30px;
            font-size: 8pt;
            text-align: center;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Exam Seat Allocation</h1>
        <h2>{{ $run->exam->title }}</h2>
        <p>Generated: {{ $run->created_at->format('d M Y, h:i A') }}</p>
        <p>Allocation Run ID: {{ $run->id }} | Mode: {{ ucfirst($run->mode) }}</p>
    </div>

    @foreach($hallGroups as $hallId => $allocations)
        @php
            $hall = $allocations->first()->hall;
        @endphp
        
        <div class="hall-section">
            <div class="hall-name">{{ $hall->name }} (Capacity: {{ $hall->capacity }})</div>
            
            <h3>Student List</h3>
            <table>
                <thead>
                    <tr>
                        <th>Seat #</th>
                        <th>Row</th>
                        <th>Col</th>
                        <th>Student Name</th>
                        <th>Class</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($allocations->sortBy('seat_number') as $allocation)
                        <tr>
                            <td>{{ $allocation->seat_number }}</td>
                            <td>{{ $allocation->row }}</td>
                            <td>{{ $allocation->column }}</td>
                            <td>{{ $allocation->student->name ?? $allocation->student->user->name }}</td>
                            <td>{{ $allocation->class_level }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <h3>Seating Chart</h3>
            <div class="grid-container">
                @php
                    $grid = $hall->getGridLayout($run->id);
                @endphp
                
                @for($r = 1; $r <= $hall->rows; $r++)
                    <div class="seat-row">
                        @for($c = 1; $c <= $hall->columns; $c++)
                            @php
                                $cell = $grid[$r][$c];
                                $student = $cell['student'];
                            @endphp
                            <div class="seat-cell {{ $student ? 'occupied' : '' }}">
                                <div class="seat-number">{{ $cell['seat_number'] }}</div>
                                @if($student)
                                    <div style="font-size: 7pt;">{{ substr($student->name ?? $student->user->name, 0, 15) }}</div>
                                @else
                                    <div style="color: #ccc;">Empty</div>
                                @endif
                            </div>
                        @endfor
                    </div>
                @endfor
            </div>
        </div>
    @endforeach

    <div class="footer">
        <p>Generated by CBT System Allocation Engine | {{ now()->format('d M Y H:i:s') }}</p>
        <p>This is an official document. Handle with confidentiality.</p>
    </div>
</body>
</html>
